language: python
python:
    - "2.7"

os: linux

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update
    - platformio lib -g install 28 #Adafruit NeoPixel
    - platformio lib -g install PubSubClient
    - platformio lib -g install HCSR04
    - platformio lib -g install NTPClient
    - platformio lib -g install WifiManager

script:
    - platformio run -e d1_mini